version: '2'
services:
    softtest-app:
        image: softtest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://softtest-postgresql:5432/softtest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    softtest-postgresql:
        extends:
            file: postgresql.yml
            service: softtest-postgresql
